# Before being able to use this hook, you will need to install `pre-commit` in your venv:
#   $ pip install pre-commit
#   OR
#   $ brew install pre-commit
#
# Place this file anywhere you want, I have it in my version controlled config,
#   then cd into your python repo and run:
#   $ ln -s ~/.config/myconfig/git-hooks/pre-commit-config.yaml $(pwd)/.pre-commit-config.yaml
# Once you have the config file in the root of your repo, install the hook:
#   $ pre-commit install
#
# If you don't want to add this file to your repo or `.gitignore`, add it to `.git/info/exclude`.
#
# When merging master into your branch, you may want to turn off this hook with `--no-verify`,;
# otherwise, you will get plenty of errors from code you do not own.
#
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: no-commit-to-branch # automatically protects main and master
      - id: pretty-format-json
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: "v5.0.0"
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
  - repo: https://github.com/psf/black
    rev: "refs/tags/22.1.0:refs/tags/22.1.0"
    hooks:
      - id: black
        additional_dependencies: [click==8.0.4]
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--indent" , "    "]
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0 # or specific git tag
    hooks:
      - id: forbid-binary # Forbid binary files from being committed
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
      - id: gitlint # Checks your git commit messages for style.
  - repo: https://github.com/myint/autoflake
    rev: "v1.4"
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variable",
          ]
